# Generated by Django 4.0.4 on 2023-10-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astronomyshow',
            options={},
        ),
        migrations.AlterField(
            model_name='astronomyshow',
            name='show_themes',
            field=models.ManyToManyField(blank=True, related_name='show_themes', to='planetarium.showtheme'),
        ),
        migrations.AlterField(
            model_name='astronomyshow',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='planetariumdome',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='planetariumdome',
            name='rows',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='planetariumdome',
            name='seats_in_row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='showsession',
            name='astronomy_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_sessions', to='planetarium.astronomyshow'),
        ),
        migrations.AlterField(
            model_name='showsession',
            name='planetarium_dome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_sessions', to='planetarium.planetariumdome'),
        ),
        migrations.AlterField(
            model_name='showtheme',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveIntegerField(),
        ),
    ]
