# Generated by Django 4.0.4 on 2023-10-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_alter_astronomyshow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astronomyshow',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='astronomyshow',
            name='show_themes',
            field=models.ManyToManyField(to='planetarium.showtheme'),
        ),
        migrations.AlterField(
            model_name='astronomyshow',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planetariumdome',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planetariumdome',
            name='rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planetariumdome',
            name='seats_in_row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='showsession',
            name='astronomy_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetarium.astronomyshow'),
        ),
        migrations.AlterField(
            model_name='showsession',
            name='planetarium_dome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetarium.planetariumdome'),
        ),
        migrations.AlterField(
            model_name='showtheme',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
